### ISSUE TITLE
FormatConverter not registering 'inferSchema' option

### ISSUE THREAD

**Issue by dsynkov** [tupol/spark-tools#7]
**Describe the bug**
I'd like to convert a CSV file to ORC with `inferSchema` set to `true` so that string values representing booleans (e.g. "true" or "True") are parsed as boolean types. I tried doing this by adding `inferSchema: true` (as well as with quotes, i.e. `inferSchema: "true"`) in the `.conf` HOCON file but when I look at my generated ORC file the columns in question still show up as string instead of Boolean.

**To Reproduce**

1. Given this [sample CSV file](https://raw.githubusercontent.com/odojoachim/Microsoft-Workshop/master/pokemon_alopez247.csv) with "isLegendary" as the boolean column, I read it in twice, once with `inferSchema` set to `true` and the other without it. You can see that with `inferSchema` as `true` the column is correctly parsed as a Boolean.

```
val csvFilePath = "s3://path/to/pokemon_alopez247.csv"

val dfNoSchema = spark.read.format("csv")
  .option("inferSchema",false)
  .option("header",true)
  .load(csvFilePath)

val dfInferSchema = spark.read.format("csv")
  .option("inferSchema",true)
  .option("header",true)
  .load(csvFilePath)

dfNoSchema.select("isLegendary").printSchema
//  |-- isLegendary: string (nullable = true)

dfInferSchema.select("isLegendary").printSchema
//  |-- isLegendary: boolean (nullable = true)
```

2. Hence, under the `input` section of the `.conf` file I likewise set `inferSchema` as:

```
 FormatConverter: {
  input: {
    path: "/path/to/input/"
    format: "csv"
    delimiter: ","
    header: true
    inferSchema: true
  }
  output: {
    path: "/path/to/output/"
    format: "orc"
    mode: "overwrite"
  }
}
```

3. When I read the converted ORC file however, the column still appears as string.

```
val dfOrc = spark.read
  .format("orc")
  .option("header",true)
  .load("/path/to/orc/file/")

dfOrc.select("isLegendary").printSchema
```

**Expected behavior**
The schema of the output ORC file with `inferSchema` set to `true` should match that of the DataFrame loaded from a CSV with `inferSchema` set to `true`.

**Comment by dsynkov** [comment]
Did not realize `inputSchema` had to be passed under `FormatConverter.input.options` section of the `.conf` file; not a bug, was simply using wrong parameter. Closing this.

**Comment by tupol** [comment]
I am glad you found the solution, and nice bug report!
